# Generated by Django 5.2.8 on 2025-11-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dadjokes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="timestamp",
            field=models.DateTimeField(blank=True),
        ),
    ]
