# Generated by Django 5.2.8 on 2025-11-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dadjokes", "0002_alter_picture_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
