# Generated by Django 5.2.6 on 2025-10-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
                ("res_add_street_num", models.TextField()),
                ("res_add_street_name", models.TextField()),
                ("res_add_apt_num", models.TextField(blank=True)),
                ("res_add_zip_code", models.TextField()),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("date_of_registration", models.DateField(blank=True, null=True)),
                ("party_affiliation", models.CharField(max_length=2)),
                ("precinct_num", models.TextField(blank=True)),
                ("v20state", models.BooleanField()),
                ("v21town", models.BooleanField()),
                ("v21primary", models.BooleanField()),
                ("v22general", models.BooleanField()),
                ("v23town", models.BooleanField()),
            ],
        ),
    ]
