# Generated by Django 5.2.6 on 2025-10-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="voter_score",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="party_affiliation",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v20state",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21town",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v22general",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v23town",
            field=models.BooleanField(default=False),
        ),
    ]
