# Generated by Django 5.2.6 on 2025-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="name",
            field=models.TextField(blank=True),
        ),
    ]
