# Generated by Django 5.2.6 on 2025-11-25 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_mealplan_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealplan",
            name="meal_idea",
        ),
        migrations.CreateModel(
            name="MealPlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.mealidea",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.mealplan",
                    ),
                ),
            ],
        ),
    ]
