# Generated by Django 5.2.8 on 2025-12-08 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_creator_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.creator",
            ),
            preserve_default=False,
        ),
    ]
